version: '3'

services:
  app:
    image: 'bitnami/laravel:latest'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=jamintu_polinema
      - DB_USERNAME=root
      - DB_PASSWORD=
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_DATABASE=jamintu_polinema
      - MARIADB_USER=user-kjm
      - MARIADB_PASSWORD=
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  mariadb_data:
    driver: local